const resourceIcons: { [key: string]: string } = {
    "Нефть": "/assets/pages/Нефть.png",
    "Газ": "/assets/pages/Газ.png",
    "Уголь": "/assets/pages/Уголь.png",
    "Железная руда": "/assets/pages/Железная руда.png",
    "Медная руда": "/assets/pages/Медная руда.png",
    "Алюминиевая руда (бокситы)": "/assets/pages/Алюминиевая руда (бокситы).png",
    "Древесина": "/assets/pages/Древесина.png",
    "Золото": "/assets/pages/Золото.png",
    "Серебро": "/assets/pages/Серебро.png",
    "Никель": "/assets/pages/Никель.png",
    "Цинк": "/assets/pages/Цинк.png",
    "Свинец": "/assets/pages/Свинец.png",
    "Олово": "/assets/pages/Олово.png",
    "Уран": "/assets/pages/Уран.png",
    "Титан": "/assets/pages/Титан.png",
    "Торф": "/assets/pages/Торф.png",
    "Графит": "/assets/pages/Графит.png",
    "Соль": "/assets/pages/Соль.png",
    "Калийные соли": "/assets/pages/Калийные соли.png",
    "Известняк": "/assets/pages/Известняк.png",
    "Глина": "/assets/pages/Глина.png",
    "Песок": "/assets/pages/Песок.png",
    "Гранит": "/assets/pages/Гранит.png",
    "Мрамор": "/assets/pages/Мрамор.png",
    "Магний": "/assets/pages/Магний.png",
    "Кобальт": "/assets/pages/Кобальт.png",
    "Литий": "/assets/pages/Литий.png",
};

export default resourceIcons;
